version: '3.8'

services:
  app:
    build:
      context: .
    image: phungvansyhb/airsense-mqtt-server
    env_file: ./.env
    ports:
      - "3001:3001"
    volumes:
      - node_modules
    stdin_open: true
    tty: true
